# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccost < Formula
  desc "Fast CLI to analyze Claude Code token usage and costs"
  homepage "https://github.com/zulerne/ccost"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zulerne/ccost/releases/download/v0.1.0/ccost_0.1.0_darwin_amd64.tar.gz"
      sha256 "7b6c358ed369042aae2e37a8ee892e912030191ce4903d9c00c8d31c435e5f0c"

      def install
        bin.install "ccost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zulerne/ccost/releases/download/v0.1.0/ccost_0.1.0_darwin_arm64.tar.gz"
      sha256 "ed6f2c6e1862a50ecaeed26d2d630e0c293a6dce13177ce927a1ca0f1c1d4571"

      def install
        bin.install "ccost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/ccost/releases/download/v0.1.0/ccost_0.1.0_linux_amd64.tar.gz"
      sha256 "127db39d454fb641bc7a6a8efde39b1edd4bf69765a1205eb19238709d21f8b9"
      def install
        bin.install "ccost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/ccost/releases/download/v0.1.0/ccost_0.1.0_linux_arm64.tar.gz"
      sha256 "ab4cb4dc294c4a8372ae6eb7b0bbb58c47a6f0af2ec3c45ff7987c2c824c6ed5"
      def install
        bin.install "ccost"
      end
    end
  end
end
