# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goseed < Formula
  desc "Scaffold Go projects with best practices"
  homepage "https://github.com/zulerne/goseed"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zulerne/goseed/releases/download/v0.1.0/goseed_0.1.0_darwin_amd64.tar.gz"
      sha256 "4b125f80106e9519ea9126f9245e68be0979f74046ceb5f3e9c76f6884226c23"

      define_method(:install) do
        bin.install "gostart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zulerne/goseed/releases/download/v0.1.0/goseed_0.1.0_darwin_arm64.tar.gz"
      sha256 "8185f3a53804a079162b05e594701a8caa24680cc47cbeed1e94f01797272098"

      define_method(:install) do
        bin.install "gostart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/goseed/releases/download/v0.1.0/goseed_0.1.0_linux_amd64.tar.gz"
      sha256 "b8784fbffb87b8e8fc0960943dde2e76cb3b221730c7ef54a6b6e2049798166a"
      define_method(:install) do
        bin.install "gostart"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/goseed/releases/download/v0.1.0/goseed_0.1.0_linux_arm64.tar.gz"
      sha256 "be8e52cb0598c4ec42c71400925cbe0c86e770db55e8899d6a01ccf717782777"
      define_method(:install) do
        bin.install "gostart"
      end
    end
  end
end
