# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccost" do
  name "ccost"
  desc "Fast CLI to analyze Claude Code token usage and costs"
  homepage "https://github.com/zulerne/ccost"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccost"

  on_macos do
    on_intel do
      url "https://github.com/zulerne/ccost/releases/download/v#{version}/ccost_#{version}_darwin_amd64.tar.gz"
      sha256 "13e49be2c3a0d11ed612e1d7f9b1967c555f686b5b31312659a679babc278a11"
    end
    on_arm do
      url "https://github.com/zulerne/ccost/releases/download/v#{version}/ccost_#{version}_darwin_arm64.tar.gz"
      sha256 "4a27c36984ab24a3873dda0b4c97820feeecb5126d06eed4a311277f3f607406"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zulerne/ccost/releases/download/v#{version}/ccost_#{version}_linux_amd64.tar.gz"
      sha256 "9d1ac777e99fc7e8b19518b47cdd06bd0a4869a374c8d1f0fb9bbdfa7d74497a"
    end
    on_arm do
      url "https://github.com/zulerne/ccost/releases/download/v#{version}/ccost_#{version}_linux_arm64.tar.gz"
      sha256 "02820fb5c2d9916dd23401273d5584f4d014c8eb71f8a18eebbc7d0360a27838"
    end
  end

  # No zap stanza required
end
