# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccost" do
  name "ccost"
  desc "Fast CLI to analyze Claude Code token usage and costs"
  homepage "https://github.com/zulerne/ccost"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccost"

  on_macos do
    on_intel do
      url "https://github.com/zulerne/ccost/releases/download/v#{version}/ccost_#{version}_darwin_amd64.tar.gz"
      sha256 "ad7f3100ab3a2ae98fa83088dfb5485f5d4f41d2e7f0cc3a59d732e694b04549"
    end
    on_arm do
      url "https://github.com/zulerne/ccost/releases/download/v#{version}/ccost_#{version}_darwin_arm64.tar.gz"
      sha256 "12c98d3b138ac360818106701b26a2bdbd2265ca61e5e67eb8e1b2ae8bfcb1dd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zulerne/ccost/releases/download/v#{version}/ccost_#{version}_linux_amd64.tar.gz"
      sha256 "655ee9ffa1fe2083e4e00b0f346b00f99ae1580b85117438e720c4005878540d"
    end
    on_arm do
      url "https://github.com/zulerne/ccost/releases/download/v#{version}/ccost_#{version}_linux_arm64.tar.gz"
      sha256 "6a50cb4d007007f95b86b30de356968719083d6c9f251ae54b06b7a0a1d558b7"
    end
  end

  # No zap stanza required
end
