# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccost" do
  name "ccost"
  desc "Fast CLI to analyze Claude Code token usage and costs"
  homepage "https://github.com/zulerne/ccost"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccost"

  on_macos do
    on_intel do
      url "https://github.com/zulerne/ccost/releases/download/v#{version}/ccost_#{version}_darwin_amd64.tar.gz"
      sha256 "ed1b53545c721970e571878dd791d6431bf86433e4470978146ce0a8b84499da"
    end
    on_arm do
      url "https://github.com/zulerne/ccost/releases/download/v#{version}/ccost_#{version}_darwin_arm64.tar.gz"
      sha256 "637f6a7487e893c0ce3cd869d392f34fba34375e78569f7385d8b0de254e0f72"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zulerne/ccost/releases/download/v#{version}/ccost_#{version}_linux_amd64.tar.gz"
      sha256 "e996dfd83c0ca5dd31126b06953768b2a7210c67f558a4e82e74941d4509fef8"
    end
    on_arm do
      url "https://github.com/zulerne/ccost/releases/download/v#{version}/ccost_#{version}_linux_arm64.tar.gz"
      sha256 "32b48ae0fcc5ce4bb9c438ce852300c2c3f90df53d7aba7d5bd20bbb9d9cf472"
    end
  end

  # No zap stanza required
end
