# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccost < Formula
  desc "Fast CLI to analyze Claude Code token usage and costs"
  homepage "https://github.com/zulerne/ccost"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zulerne/ccost/releases/download/v0.7.0/ccost_0.7.0_darwin_amd64.tar.gz"
      sha256 "0882321173db75824cc4e3695f0c26d1049fde7c36f41edeb95bbbe1657dd1d1"

      def install
        bin.install "ccost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zulerne/ccost/releases/download/v0.7.0/ccost_0.7.0_darwin_arm64.tar.gz"
      sha256 "3dddc9e0bfabd5f00e7d5133359cb0b7e43f484d036715d6ce1bc6ca5d33abc9"

      def install
        bin.install "ccost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/ccost/releases/download/v0.7.0/ccost_0.7.0_linux_amd64.tar.gz"
      sha256 "77a05db7c13cb8c9e915d602820c588613b5652daeb01c05c81bf5ba7c547b98"
      def install
        bin.install "ccost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/ccost/releases/download/v0.7.0/ccost_0.7.0_linux_arm64.tar.gz"
      sha256 "8e977acaff71d86024defcacdfdb1557111d532e00b200de4db66b3778adb9ff"
      def install
        bin.install "ccost"
      end
    end
  end
end
