# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccost < Formula
  desc "Fast CLI to analyze Claude Code token usage and costs"
  homepage "https://github.com/zulerne/ccost"
  version "0.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zulerne/ccost/releases/download/v0.8.1/ccost_0.8.1_darwin_amd64.tar.gz"
      sha256 "d7cb5e40d15b3765966e55f1840215246782069666ffba2a5f19f78e47796f90"

      def install
        bin.install "ccost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zulerne/ccost/releases/download/v0.8.1/ccost_0.8.1_darwin_arm64.tar.gz"
      sha256 "3483d8d50e44dd230d99660359f5ecbe5baa54afb81ad9f7a09bd9be889d6c00"

      def install
        bin.install "ccost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/ccost/releases/download/v0.8.1/ccost_0.8.1_linux_amd64.tar.gz"
      sha256 "37ec94b3e3d6eefa98949ff970097440ed45f1978bfb8a828ffabdf46c5f9f8b"
      def install
        bin.install "ccost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/ccost/releases/download/v0.8.1/ccost_0.8.1_linux_arm64.tar.gz"
      sha256 "09ed39b558d4ba9c0093c38eb8c9215e8870cd2e91ad9119fcbf2327f78d6c06"
      def install
        bin.install "ccost"
      end
    end
  end
end
