# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccost < Formula
  desc "Fast CLI to analyze Claude Code token usage and costs"
  homepage "https://github.com/zulerne/ccost"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zulerne/ccost/releases/download/v0.5.0/ccost_0.5.0_darwin_amd64.tar.gz"
      sha256 "1cddac6458fc9b12d44006a6bba360be5c234f9934a80865f927bda5235510cd"

      def install
        bin.install "ccost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zulerne/ccost/releases/download/v0.5.0/ccost_0.5.0_darwin_arm64.tar.gz"
      sha256 "18a55b245020b8176a141af2b50252a478df4c96be501e813bcc3aa4d6300b9b"

      def install
        bin.install "ccost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/ccost/releases/download/v0.5.0/ccost_0.5.0_linux_amd64.tar.gz"
      sha256 "7859ed46518b10e714fddec2424ca07717d429c27be629580a46a5235dd21edb"
      def install
        bin.install "ccost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/ccost/releases/download/v0.5.0/ccost_0.5.0_linux_arm64.tar.gz"
      sha256 "65e68a61b7489a53e3b817b0dbc4178501b7e205b4d934c5acc038b12465487a"
      def install
        bin.install "ccost"
      end
    end
  end
end
