# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goseed < Formula
  desc "Scaffold Go projects with best practices"
  homepage "https://github.com/zulerne/goseed"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zulerne/goseed/releases/download/v0.6.0/goseed_0.6.0_darwin_amd64.tar.gz"
      sha256 "69f245950300aefa4ef567b6506e427f7421eb7dcf55526a7d2d148f4bd6867d"

      define_method(:install) do
        bin.install "goseed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zulerne/goseed/releases/download/v0.6.0/goseed_0.6.0_darwin_arm64.tar.gz"
      sha256 "412eb0286c444168d4f387c55221a60201c0d9f2c86d9065e1904e077ca6b107"

      define_method(:install) do
        bin.install "goseed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/goseed/releases/download/v0.6.0/goseed_0.6.0_linux_amd64.tar.gz"
      sha256 "14a0eba223d4901135cf0c21411369afc44cc8337648cecdd5631adac9cad8ba"
      define_method(:install) do
        bin.install "goseed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/goseed/releases/download/v0.6.0/goseed_0.6.0_linux_arm64.tar.gz"
      sha256 "83e11ee9b2058ecece45e19a93843b7d0770d71b2c31da7923fb291bb9ff272a"
      define_method(:install) do
        bin.install "goseed"
      end
    end
  end
end
