# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goseed < Formula
  desc "Scaffold Go projects with best practices"
  homepage "https://github.com/zulerne/goseed"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zulerne/goseed/releases/download/v0.2.0/goseed_0.2.0_darwin_amd64.tar.gz"
      sha256 "9ce1acf441e55e787bc21d133475375d4986c9898b34fee8f16192fb009679c1"

      define_method(:install) do
        bin.install "goseed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zulerne/goseed/releases/download/v0.2.0/goseed_0.2.0_darwin_arm64.tar.gz"
      sha256 "d9221785c7da65d36b71347224641e6344c62ee63bc4e13361b62e7218c826c5"

      define_method(:install) do
        bin.install "goseed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/goseed/releases/download/v0.2.0/goseed_0.2.0_linux_amd64.tar.gz"
      sha256 "04484e6cfdfb754f518284bb59ae42acc0bf8dec6f0601601cf856fe4b8f5f11"
      define_method(:install) do
        bin.install "goseed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulerne/goseed/releases/download/v0.2.0/goseed_0.2.0_linux_arm64.tar.gz"
      sha256 "30fdabf0374b3bb0da133c73a5e4cb9c813e653f8d2bd3562e50d2a0026bfd9a"
      define_method(:install) do
        bin.install "goseed"
      end
    end
  end
end
